postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  env_file: .env
  ports:
    - "5432:5432"

imager:
  restart: always
  build: ./imager/
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  environment:
    - EMAIL_HOST_PASSWORD=password
    - DATABASE_HOST=postgres
  command: /usr/local/bin/gunicorn imager.wsgi:application -w 2 -b :8000
  env_file: .env
  links:
    - postgres:postgres

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - imager
  links:
    - imager:imager

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: /bin/true
