imager:
  restart: always
  build: ./imager/
  expose:
    - "8000"
  links:
    - postgres:postgres
  env_file: .env
  command: /usr/local/bin/gunicorn imager.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
